### ISSUE TITLE
[Feature]: Dynamically change in wallpaper according  to change on weather.

### ISSUE THREAD

**Issue by ashutosh-3474** [OPCODE-Open-Spring-Fest/Weather_Forecast-App#3]
### So, what is it about?

# Description
The current version of the app have a static wallpaper which is same for all  weather condition, we may build a algorithm to change wallpaper dynamically as weather change.
# Detail

- [ ] **Algorithm:** Build an algorithm to change the wallpaper dynamically  as weather changes, using  description property of weather (Refer to [docs](https://openweathermap.org/forecast5) for details of  properties).
# Expected Benefit
App will be  more attractive and user friendly.
# Additional Notes
* Considerations such as user interface design, error handling, and performance optimization should be taken into account during the implementation process.
* make sure wallpaper matches the weather condition.
* For building the algorithm, take the reference of the algorithm already used in app and documentation of weather plugin([docs](https://pub.dev/packages/weather))
# Deadline
[2 days]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ashutosh4192** [comment]
@ashutosh-3474 kindly assign me this issue

**Comment by ashutosh-3474** [comment]
Sure @Ashutosh4192 , try to complete till 14/04/2024
